src/accounts/urls.py
from django.urls import path
from .views import UserCreateView, UserDetailView, UserListView, UserUpdateView, UserDeleteView, UserLoginView,login_view

app_name = 'accounts'

urlpatterns = [
    path('create/', UserCreateView.as_view(), name='create'),
    path('login/', login_view, name='login'),
    path('list/', UserListView.as_view(), name='list'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', UserDeleteView.as_view(), name='delete'),
]

src/accounts/models.py
# accounts.models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from .managers import UserManager


class User(AbstractBaseUser):
    first_name = models.CharField(max_length=120, verbose_name='First name')
    last_name = models.CharField(max_length=120, verbose_name='last name')
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    phone_number = models.IntegerField()
    picture = models.ImageField(upload_to='users/pictures/', null=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False) # a admin user; non super-user
    admin = models.BooleanField(default=False) # a superuser
    # notice the absence of a "Password field", that's built in.

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # Email & Password are required by default.

    objects = UserManager()


    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active


    def get_absolute_url(self):
        return reverse("accounts:detail", kwargs={"pk": self.pk})

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import (
    authenticate,
    get_user_model

)
from .models import User


class RegisterForm(forms.ModelForm):
    picture = forms.ImageField(label='Profile Picture')
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'email', 'picture',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'email','picture')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('first_name','last_name','phone_number','email', 'picture','password', 'active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

src/accounts/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)
from .forms import RegisterForm, UserLoginForm
from .models import User
# Create your views here.


class UserCreateView(CreateView):

    form_class = RegisterForm
    template_name = 'accounts/authentication/signup.html'

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save()
        return super().form_valid(form)

class UserLoginView(LoginView):

    form_class = UserLoginForm
    template_name = 'accounts/authentication/login.html'

    success_url = 'home'
    # def post(self, request, **kwargs):
    #     print(kwargs)


    def form_valid(self, form):
        """Security check complete. Log the user in."""
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        login(request, user)
        return success_url

def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    print(form.cleaned_data.get('email'))
    if form.is_valid():
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        print(f'wooozzzaaaa---- {email}')
        login(request, user)
        if next:
            return redirect(next)
        return redirect('/')

    context = {
        'form': form,
    }
    return render(request, "accounts/authentication/login.html", context)



class UserListView(ListView):
    model = User
    template_name = "accounts/account_list.html"


class UserDetailView(DetailView):

    model = User
    # queryset = User.objects.filter(email=request.kwargs.get('email'))
    template_name = 'accounts/account_detail.html'

    # def get_object(self, **kwargs):
    #     email = kwargs.get('email')
    #     object = get_object_or_404(User, email=email)
    #     return object

    def get_queryset(self, **kwargs):

		# if self.request.user.is_authenticated:
	    return User.objects.filter(pk=self.kwargs.get('pk'))
		# else:
		# 	return User.objects.none()


class UserUpdateView(UpdateView):
    model = User
    form_class = RegisterForm
    template_name = "accounts/account_update.html"

    def get_queryset(self, **kwargs):

		# if self.request.user.is_authenticated:
	    return User.objects.filter(pk=self.kwargs.get('pk'))


class UserDeleteView(DeleteView):
    model = User
    template_name = "accounts/account_delete.html"


    def get_queryset(self, **kwargs):

		# if self.request.user.is_authenticated:
	    return User.objects.filter(pk=self.kwargs.get('pk'))

src/accounts/templates/accounts/account_delete.html
{% extends 'base.html' %}

{% block title %}Account Detail{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center bd-highlight">
    <div class="card">
        <div class="card-header">
            <h3>User Delete</h3>
        </div>
        <div class="card-body d-flex justify-content-start align-items-center">
            <div class="user__picture mr-5">
                <img src="{{ object.picture.url }}" class="rounded-circle" alt="Profile Picture"
                    style="width: 200px; height:200px;">
            </div>
            <div class="user__detail align-self-center">
                <dl class='row'>
                    <dt class="col-sm-3">First Name</dt>
                    <dd class='col-sm-9'>{{ object.first_name }} </dd>

                    <dt class="col-sm-3">Last Name</dt>
                    <dd class='col-sm-9'>{{ object.last_name }} </dd>

                    <dt class="col-sm-3">Email</dt>
                    <dd class='col-sm-9'>{{ object.email }} </dd>

                    <dt class="col-sm-3">Phone number</dt>
                    <dd class='col-sm-9'>{{ object.phone_number }} </dd>
                </dl>
            </div>
        </div>
    </div>


</div>
{% endblock %}

src/accounts/templates/accounts/account_detail.html
{% extends 'base.html' %}

{% block title %}Account Detail{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center bd-highlight">
    <div class="card">
        <div class="card-header">
            <h3>User Detail</h3>
        </div>
        <div class="card-body d-flex justify-content-start align-items-center">
            <div class="user__picture mr-5">
                <img src="{{ object.picture.url }}" class="rounded-circle" alt="Profile Picture"
                    style="width: 200px; height:200px;">
            </div>
            <div class="user__detail align-self-center">
                <dl class='row'>
                    <dt class="col-sm-3">First Name</dt>
                    <dd class='col-sm-9'>{{ object.first_name }} </dd>

                    <dt class="col-sm-3">Last Name</dt>
                    <dd class='col-sm-9'>{{ object.last_name }} </dd>

                    <dt class="col-sm-3">Email</dt>
                    <dd class='col-sm-9'>{{ object.email }} </dd>

                    <dt class="col-sm-3">Phone number</dt>
                    <dd class='col-sm-9'>{{ object.phone_number }} </dd>
                </dl>
            </div>
        </div>
    </div>


</div>
{% endblock %}

src/accounts/templates/accounts/account_list.html
{% extends 'base.html' %}

{% block title %}Account Detail{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center bd-highlight">
    <div class="container p-5">
        <div class="card">
            <div class="card-header">
                <h3>User List</h3>
            </div>
            <div class="card-body">
               <table class="table table-hover">
                   <thead>
                       <tr>
                           <th scope="col">#</th>
                           <th scope="col">First</th>
                           <th scope="col">Last</th>
                           <th scope="col">Email</th>
                           <th scope='col'>Phone number</th>
                           <th></th>
                       </tr>
                   </thead>
                   <tbody>
                       {% for object in object_list %}
                       <tr>
                            <th scope="row">{{ object.id }}</th>
                            <td>{{ object.first_name }}</td>
                            <td>{{ object.last_name }}</td>
                            <td><a href="{% url 'accounts:detail' object.pk %}">{{ object.email }}</a></td>
                            <td>{{ object.phone_number }}</td>
                            <td>
                                <a href="{% url 'accounts:detail' object.pk %}" class="btn  btn-sm bg-info">View</a>
                                <a href="{% url 'accounts:update' object.pk %}" class="btn btn-secondary btn-sm">Edit</a>
                                <a href="{% url 'accounts:delete' object.pk %}" class="btn btn-danger btn-sm">Delete</a>
                            </td>
                       </tr>
                       {% endfor %}
                   </tbody>
               </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/account_update.html
{% extends 'base.html' %}

{% block title %}Account Detail{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center bd-highlight">
    <div class="card">
        <div class="card-header">
            <h3>User Update</h3>
        </div>
        <div class="card-body d-flex justify-content-start align-items-center">
            <div class="user__picture mr-5">
                <img src="{{ object.picture.url }}" class="rounded-circle" alt="Profile Picture"
                    style="width: 200px; height:200px;">
            </div>
            <div class="user__detail align-self-center">
                <dl class='row'>
                    <dt class="col-sm-3">First Name</dt>
                    <dd class='col-sm-9'>{{ object.first_name }} </dd>

                    <dt class="col-sm-3">Last Name</dt>
                    <dd class='col-sm-9'>{{ object.last_name }} </dd>

                    <dt class="col-sm-3">Email</dt>
                    <dd class='col-sm-9'>{{ object.email }} </dd>

                    <dt class="col-sm-3">Phone number</dt>
                    <dd class='col-sm-9'>{{ object.phone_number }} </dd>
                </dl>
            </div>
        </div>
    </div>


</div>
{% endblock %}